/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApplyRouteImport } from './routes/apply'

const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/apply': typeof ApplyRoute
}
export interface FileRoutesByTo {
  '/apply': typeof ApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/apply': typeof ApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/apply'
  fileRoutesByTo: FileRoutesByTo
  to: '/apply'
  id: '__root__' | '/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApplyRoute: typeof ApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApplyRoute: ApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
